/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package application.Vue;

import application.Modele.BaseLayer.Fichier;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author NNJeremy
 */
public class AdminGestionFichier extends javax.swing.JPanel {

    /**
     * Creates new form AdminGestionFichier
     */
    public AdminGestionFichier(FenPrincipale fenprinc) {
        initComponents();
        this.ancetre = fenprinc;
        this.initJlistFichier();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_fichier = new javax.swing.JList();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jButton_Suppr = new javax.swing.JButton();

        jLabel_titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titre.setText("Gestion des fichiers");

        jLabel2.setText("Selection :");

        jList_fichier.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList_fichier);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setText("Action :");

        jButton_Suppr.setText("Supprimer");
        jButton_Suppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SupprActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton_Suppr)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_titre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_Suppr)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SupprActionPerformed

        try {
        
                List selected = this.jList_fichier.getSelectedValuesList();
                Iterator i = selected.iterator();

                while(i.hasNext()){

                        String cheminSelected = (String) i.next();
                        Fichier fichierSelected = this.ancetre.application().getGestionFichier().getFichierByChemin(cheminSelected);
                        this.ancetre.application().getGestionFichier().deleteFichier(fichierSelected);

                }
                
                this.initJlistFichier();
                
            } catch (RemoteException ex) {
                Logger.getLogger(AdminGestionProfil.class.getName()).log(Level.SEVERE, null, ex);
            }    
        
    }//GEN-LAST:event_jButton_SupprActionPerformed

    private void initJlistFichier() {
        
        try {
            
            ArrayList<Fichier> arrayListProfil = this.ancetre.application().getGestionFichier().getCatalogue();
                
            Iterator it = arrayListProfil.iterator();
            int cpt = 0;
            DefaultListModel alm = new javax.swing.DefaultListModel();

                while (it.hasNext()){
                    Fichier fichier = (Fichier) it.next();
                    alm.add(cpt, fichier.getChemin());
                    cpt++;
                }
            
            this.jList_fichier.setModel(alm);
            
        } catch (RemoteException ex) {
            Logger.getLogger(AdminGestionProfil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Suppr;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_titre;
    private javax.swing.JList jList_fichier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
    private FenPrincipale ancetre;
}
