/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package application.Vue;

import application.Modele.BaseLayer.Categorie;
import application.Modele.BaseLayer.Message;
import application.Modele.BaseLayer.Sujet;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author NNJeremy
 */
public class AdminGestionForum extends javax.swing.JPanel {

    /**
     * Creates new form AdminGestionForum
     */
    public AdminGestionForum(FenPrincipale fenprinc) {
        initComponents();
        this.ancetre = fenprinc;
        initBoxTopic();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_Topic = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_Sujet = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_Message = new javax.swing.JList();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jButton_Suppr = new javax.swing.JButton();

        jLabel_Titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titre.setText("Gestion du Forum");

        jLabel2.setText("Selection du topic :");

        jComboBox_Topic.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Informatique", "Cinema", "Sante", "FAQ", "Autre" }));
        jComboBox_Topic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_TopicMouseClicked(evt);
            }
        });
        jComboBox_Topic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TopicActionPerformed(evt);
            }
        });

        jLabel3.setText("Selection du sujet :");

        jComboBox_Sujet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Sujet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_SujetActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setText("Selection du message :");

        jScrollPane1.setViewportView(jList_Message);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setText("Action :");

        jButton_Suppr.setText("Supprimer");
        jButton_Suppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SupprActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_Topic, 0, 164, Short.MAX_VALUE)
                    .addComponent(jComboBox_Sujet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton_Suppr)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Titre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                            .addComponent(jSeparator3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox_Topic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox_Sujet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_Suppr)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SupprActionPerformed
            try {
                
                List selected = this.jList_Message.getSelectedValuesList();
                Iterator i = selected.iterator();

                while(i.hasNext()){
                    String messageSelected = (String) i.next();
                    Message msgSelected = this.selectedSujet.getMsgByNom(messageSelected);
                    this.ancetre.application().getForum().deleteMessage(msgSelected);
                }
                
                this.initJlistMsg();
                
            } catch (RemoteException ex) {
                Logger.getLogger(AdminGestionForum.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jButton_SupprActionPerformed

    private void jComboBox_TopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TopicActionPerformed
        
        try {
        
            this.selectedTopic = this.ancetre.application().getForum().getCategorieByNom((String)this.jComboBox_Topic.getSelectedItem());
            initBoxSujet();
            
        } catch (RemoteException ex) {
            Logger.getLogger(AdminGestionProfil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox_TopicActionPerformed

    private void jComboBox_TopicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_TopicMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_TopicMouseClicked

    private void jComboBox_SujetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_SujetActionPerformed

            this.selectedSujet = this.selectedTopic.getSujetByNom((String)this.jComboBox_Sujet.getSelectedItem());
            initJlistMsg();
        
    }//GEN-LAST:event_jComboBox_SujetActionPerformed

    private void initBoxTopic() {
        
        try {
            
            ArrayList<Categorie> arrayListCategorie = this.ancetre.application().getForum().getCatalogueCategorie();
                
            Iterator it = arrayListCategorie.iterator();
            int cpt = 0;
            DefaultComboBoxModel dcbm = new javax.swing.DefaultComboBoxModel();

                while (it.hasNext()){
                    Categorie categorie = (Categorie) it.next();
                    dcbm.addElement(categorie.getNom());
                    
                        if (cpt == 0)
                            selectedTopic = categorie;
                    
                    cpt++;
                }
            
            this.jComboBox_Topic.setModel(dcbm);
            
            initBoxSujet();
            
        } catch (RemoteException ex) {
            Logger.getLogger(AdminGestionProfil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void initBoxSujet() {
            
            ArrayList<Sujet> arrayListSujet = this.selectedTopic.getSujet();
                
            Iterator it = arrayListSujet.iterator();
            int cpt = 0;
            DefaultComboBoxModel dcbm = new javax.swing.DefaultComboBoxModel();

                while (it.hasNext()){
                    Sujet sujet = (Sujet) it.next();
                    dcbm.addElement(sujet.getNom());
                    
                        if (cpt == 0)
                            selectedSujet = sujet;
                    
                    cpt++;
                }
            
            this.jComboBox_Sujet.setModel(dcbm);
            
            if (selectedSujet != null)
            initJlistMsg();

    }
    
    private void initJlistMsg() {
        
            ArrayList<Message> arrayListMessage = this.selectedSujet.getMessage();
                
            Iterator it = arrayListMessage.iterator();
            int cpt = 0;
            DefaultListModel alm = new javax.swing.DefaultListModel();

                while (it.hasNext()){
                    Message message = (Message) it.next();
                    alm.add(cpt, message.getMessage());
                    cpt++;
                }
            
            this.jList_Message.setModel(alm);

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Suppr;
    private javax.swing.JComboBox jComboBox_Sujet;
    private javax.swing.JComboBox jComboBox_Topic;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Titre;
    private javax.swing.JList jList_Message;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
    private FenPrincipale ancetre;
    private Categorie selectedTopic; 
    private Sujet selectedSujet; 
}
