/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FAQ.java
 *
 * Created on 26 avr. 2012, 22:35:58
 */
package application.Vue;

import application.Modele.BaseLayer.Categorie;
import application.Modele.BaseLayer.Message;
import application.Modele.BaseLayer.Sujet;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author NNJeremy
 */
public class FAQ extends javax.swing.JPanel {
 private String tmp = "";
    /**
     * Creates new form FAQ
     */
    
    private FenPrincipale f;
    public FAQ() {
        initComponents();
    }
    
    public void setFen(FenPrincipale f){
        this.f=f;
        afficherJlist();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Texte = new javax.swing.JTextArea();
        jLabel_Faq = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_Sujet = new javax.swing.JList();
        jButton_NouveauSujet = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FAQ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTextArea_Texte.setColumns(20);
        jTextArea_Texte.setRows(5);
        jTextArea_Texte.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea_Texte);

        jLabel_Faq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Faq.setText("FAQ");

        jList_Sujet.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_SujetValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList_Sujet);

        jButton_NouveauSujet.setText("Nouveau Sujet");
        jButton_NouveauSujet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NouveauSujetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton_NouveauSujet))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Faq, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Faq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_NouveauSujet))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_NouveauSujetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NouveauSujetActionPerformed
        try {
            FenNouveauSujet nouvSuj = new FenNouveauSujet();
            nouvSuj.setFenetrePrincipal(f);
            nouvSuj.setCategorie(this.f.application().getForum().getCategorieByNom("FAQ"));
            nouvSuj.setFenPreced(this);
            nouvSuj.setVisible(true);
        } catch (RemoteException ex) {
            Logger.getLogger(FAQ.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton_NouveauSujetActionPerformed

    private void jList_SujetValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_SujetValueChanged
        
        afficherMessage();
        
    }//GEN-LAST:event_jList_SujetValueChanged

    public void afficherMessage(){
        try {
            String titreSujet = (String) this.jList_Sujet.getSelectedValue();
            ArrayList<Sujet> tousLesSujets = this.f.application().getForum().getCategorieByNom("FAQ").getSujet();
            Iterator<Sujet> itSujet = tousLesSujets.iterator();
            while (itSujet.hasNext()) {
                Sujet sujetActuel = itSujet.next();
                if (sujetActuel.getNom().equalsIgnoreCase(titreSujet)) {
                    ArrayList<Message> tousLesMessages = sujetActuel.getMessage();
                    Iterator<Message> itMessage = tousLesMessages.iterator();
                    String affichageMessage = "";
                    while (itMessage.hasNext()) {
                        Message messageActuel = itMessage.next();
                        affichageMessage += messageActuel.toString() + "\n";
                    }
                    this.jTextArea_Texte.setText(affichageMessage);
                    this.sujetActuel = sujetActuel;
                }
            }
        } catch (RemoteException ex) {
            Logger.getLogger(FAQ.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_NouveauSujet;
    private javax.swing.JLabel jLabel_Faq;
    private javax.swing.JList jList_Sujet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea_Texte;
    // End of variables declaration//GEN-END:variables
    private Sujet sujetActuel;
    
    public void afficherJlist() {
        try {
            if(this.f == null)
                System.out.println("error");
            
            Categorie c = this.f.application().getForum().getCategorieByNom("FAQ");
             ArrayList<Sujet> sujetLis = c.getSujet();
                
            Iterator it = sujetLis.iterator();
            int cpt = 0;
            DefaultListModel alm = new javax.swing.DefaultListModel();

                while (it.hasNext()){
                    Sujet sujet = (Sujet) it.next();
                    alm.add(cpt, sujet.getNom());
                    cpt++;
                }
            
            this.jList_Sujet.setModel(alm);
            
        } catch (RemoteException ex) {
            Logger.getLogger(FAQ.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void testAfficherJlist() {
        Categorie c = new Categorie(1, "", "");
        ArrayList<Sujet> sujetLis = c.getSujet();
        LinkedList<String> sujets = new LinkedList<String>();

        for (int i = 0; i < 5; i++) {tmp = "toto" + "\n";sujets.add(tmp);}
        String[] tab = (String[]) sujets.toArray();
        jList_Sujet = new JList(tab);

    }
    
      public void afficherJTextArea_Texte() { 
       Sujet su=new Sujet("", TOOL_TIP_TEXT_KEY, null, null, null);
      ArrayList<Message> LesMessages = su.getMessage();
      Iterator<Message> itMessage =LesMessages.iterator(); 
      String affMessage = ""; 
      while (itMessage.hasNext()) { 
          Message message= itMessage.next(); 
          affMessage +=message.toString() + "\n"; 
      }
     jTextArea_Texte.setText(affMessage);
     
     
     
      }
     
}
     
    


