/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FenDecoMembre.java
 *
 * Created on 27 avr. 2012, 10:34:13
 */
package application.Vue;

import application.Modele.BaseLayer.Profil;
import java.rmi.RemoteException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author NNJeremy
 */
public class FenDecoMembre extends javax.swing.JPanel {

    /** Creates new form FenDecoMembre */
    public FenDecoMembre(FenPrincipale fenprinc) {
        initComponents();
        this.ancetre = fenprinc;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Iscription = new javax.swing.JButton();
        _Connexion = new javax.swing.JButton();
        jLabel_Mdp = new javax.swing.JLabel();
        jTextField_Pseudo = new javax.swing.JTextField();
        jPasswordField_Mdp = new javax.swing.JPasswordField();
        jLabel_Pseudo = new javax.swing.JLabel();

        jButton_Iscription.setText("Inscription");
        jButton_Iscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IscriptionActionPerformed(evt);
            }
        });

        _Connexion.setText("Connexion");
        _Connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _ConnexionActionPerformed(evt);
            }
        });

        jLabel_Mdp.setText("Mot de passe : ");

        jLabel_Pseudo.setText("Pseudo : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(jLabel_Pseudo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Mdp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField_Mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(_Connexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Iscription)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Iscription)
                    .addComponent(_Connexion)
                    .addComponent(jLabel_Mdp)
                    .addComponent(jTextField_Pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField_Mdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Pseudo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jButton_IscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IscriptionActionPerformed
    Inscription ins = new Inscription(ancetre);
    ins.setVisible(true);
}//GEN-LAST:event_jButton_IscriptionActionPerformed

private void _ConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__ConnexionActionPerformed
    String pseudo = jTextField_Pseudo.getText();
    String mdp = new String(jPasswordField_Mdp.getPassword());
        try {
            Profil pr;
            if ((pr = ancetre.application().getGestionProfil().login(pseudo, mdp)) != null)
                ancetre.switchPanelLogin(pr);
            else{
                JOptionPane.showMessageDialog(this, "login incorrect", "Echec de l'authentification", JOptionPane.WARNING_MESSAGE);
            }
        } catch (RemoteException ex) {
            ex.printStackTrace();
        }
}//GEN-LAST:event__ConnexionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _Connexion;
    private javax.swing.JButton jButton_Iscription;
    private javax.swing.JLabel jLabel_Mdp;
    private javax.swing.JLabel jLabel_Pseudo;
    private javax.swing.JPasswordField jPasswordField_Mdp;
    private javax.swing.JTextField jTextField_Pseudo;
    // End of variables declaration//GEN-END:variables
    private FenPrincipale ancetre;
}
