/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FenNouveauSujet.java
 *
 * Created on 26 avr. 2012, 23:05:05
 */
package application.Vue;

import application.Modele.BaseLayer.Categorie;
import application.Modele.BaseLayer.Message;
import application.Modele.BaseLayer.Profil;
import application.Modele.BaseLayer.Sujet;
import application.Modele.ModuleLayer.ForumModule;
import java.rmi.RemoteException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author NNJeremy
 */
public class FenNouveauSujet extends javax.swing.JFrame {

    /** Creates new form FenNouveauSujet */
    public FenNouveauSujet() {
        initComponents();
        this.setLocationRelativeTo(getParent());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_FAQ = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_Sujet = new javax.swing.JLabel();
        jTextField_Sujet = new javax.swing.JTextField();
        jLabel_Question = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Question = new javax.swing.JTextArea();
        jButton_Envoyer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nouveau Sujet");

        jLabel_FAQ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FAQ.setText("Nouveau Sujet");

        jLabel_Sujet.setText("Sujet :");

        jLabel_Question.setText("Question :");

        jTextArea_Question.setColumns(20);
        jTextArea_Question.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Question);

        jButton_Envoyer.setText("Envoyer");
        jButton_Envoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EnvoyerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_FAQ, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(jTextField_Sujet, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(jButton_Envoyer, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Sujet)
                            .addComponent(jLabel_Question))
                        .addGap(0, 217, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_FAQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Sujet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Sujet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Question)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Envoyer)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_EnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EnvoyerActionPerformed
        try {
            // TODO add your handling code here:
            Profil profilMsg;
            if (ancetre.profil() == null)
                profilMsg = this.ancetre.application().getGestionProfil().getProfilByPseudo("Visiteur");
            else
                profilMsg = ancetre.profil();
                    
            
            Sujet sujet = new Sujet(this.jTextField_Sujet.getText(), this.jTextArea_Question.getText(), this.categorieConcernee, profilMsg, new Date());
            
            ancetre.application().getForum().ajouterSujet(sujet);
            
            sujet = this.ancetre.application().getForum().getCategorieByNom(this.categorieConcernee.getNom()).getSujetByNom(this.jTextField_Sujet.getText());
            
            Message mess = new Message(this.jTextArea_Question.getText(), sujet, profilMsg, new Date());
            ancetre.application().getForum().ajouterMessage(mess);
            
            if(this.FenPreced instanceof PanelForum)
                ((PanelForum)this.FenPreced).affichierSujet();
            
            if(this.FenPreced instanceof FAQ)
                ((FAQ)this.FenPreced).afficherJlist();                
            
            this.dispose();
        } catch (RemoteException ex) {
            Logger.getLogger(FenNouveauSujet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_EnvoyerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenNouveauSujet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenNouveauSujet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenNouveauSujet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenNouveauSujet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FenNouveauSujet().setVisible(true);
            }
        });
    }
    
    public void setFenetrePrincipal(FenPrincipale fen){
        this.ancetre =fen;
    }
    
    public void setCategorie(Categorie cat){
        this.categorieConcernee=cat;
    }
    
    public void setFenPreced(javax.swing.JPanel FenPreced){
        this.FenPreced = FenPreced;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Envoyer;
    private javax.swing.JLabel jLabel_FAQ;
    private javax.swing.JLabel jLabel_Question;
    private javax.swing.JLabel jLabel_Sujet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea_Question;
    private javax.swing.JTextField jTextField_Sujet;
    // End of variables declaration//GEN-END:variables


    private Categorie categorieConcernee;
    private FenPrincipale ancetre;
    private javax.swing.JPanel FenPreced;
}
