/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package application.Vue;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author NNJeremy
 */
public class FenProfil extends javax.swing.JPanel {

    /**
     * Creates new form FenProfil
     */
    public FenProfil(FenPrincipale fenprinc) {
        initComponents();
        this.ancetre = fenprinc;
        jTextField_Pseudo.setText(ancetre.profil().getPseudo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Pseudo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_titre2 = new javax.swing.JLabel();
        jLabel_Mdp1 = new javax.swing.JLabel();
        jLabel_Mdp2 = new javax.swing.JLabel();
        jLabel_Mdp3 = new javax.swing.JLabel();
        jPasswordField_confirmNewMdp = new javax.swing.JPasswordField();
        jPasswordField_newMdp = new javax.swing.JPasswordField();
        jPasswordField_OldMdp = new javax.swing.JPasswordField();
        jTextField_Pseudo = new javax.swing.JTextField();
        jButton_Enrg = new javax.swing.JButton();
        jButton_Annuler = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion du profil", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jLabel_Pseudo.setText("Pseudo : ");

        jLabel_titre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titre2.setText("Changer de mot de passe");

        jLabel_Mdp1.setText("Mot de passe actuel : ");

        jLabel_Mdp2.setText("Nouveau mot de passe : ");

        jLabel_Mdp3.setText("Confirmez Nouveau mot de passe : ");

        jTextField_Pseudo.setEditable(false);
        jTextField_Pseudo.setEnabled(false);
        jTextField_Pseudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PseudoActionPerformed(evt);
            }
        });

        jButton_Enrg.setText("Enregistrer");
        jButton_Enrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EnrgActionPerformed(evt);
            }
        });

        jButton_Annuler.setText("Annuler");
        jButton_Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
            .addComponent(jLabel_titre2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Pseudo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Mdp2)
                                    .addComponent(jLabel_Mdp1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPasswordField_OldMdp, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(jPasswordField_newMdp)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel_Mdp3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_Enrg)
                                    .addComponent(jPasswordField_confirmNewMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Annuler)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Pseudo)
                    .addComponent(jTextField_Pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_titre2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Mdp1)
                    .addComponent(jPasswordField_OldMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Mdp2)
                    .addComponent(jPasswordField_newMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Mdp3)
                    .addComponent(jPasswordField_confirmNewMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Enrg)
                    .addComponent(jButton_Annuler))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_PseudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PseudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PseudoActionPerformed

    private void jButton_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AnnulerActionPerformed
        
        this.ancetre.returnForum();
        
    }//GEN-LAST:event_jButton_AnnulerActionPerformed

    private void jButton_EnrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EnrgActionPerformed
        try {
            String newmdp = new String(jPasswordField_newMdp.getPassword());
            if (new String(jPasswordField_OldMdp.getPassword()).equals(ancetre.application().getGestionProfil().getProfilByPseudo(ancetre.profil().getPseudo()).getPassword()) &&
                    newmdp.equals(new String(jPasswordField_confirmNewMdp.getPassword()))){
                if(ancetre.application().getGestionProfil().changerMDP(ancetre.profil(), newmdp)){
                    ancetre.updateProfil();
                    JOptionPane.showConfirmDialog(this, "Le changement de votre mot de passe a été effectué", "Confirmation", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this, "Probleme de connexion au serveur", "Erreur Changement mot de passe", JOptionPane.ERROR_MESSAGE);
        }
        this.ancetre.returnForum();
        
    }//GEN-LAST:event_jButton_EnrgActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Annuler;
    private javax.swing.JButton jButton_Enrg;
    private javax.swing.JLabel jLabel_Mdp1;
    private javax.swing.JLabel jLabel_Mdp2;
    private javax.swing.JLabel jLabel_Mdp3;
    private javax.swing.JLabel jLabel_Pseudo;
    private javax.swing.JLabel jLabel_titre2;
    private javax.swing.JPasswordField jPasswordField_OldMdp;
    private javax.swing.JPasswordField jPasswordField_confirmNewMdp;
    private javax.swing.JPasswordField jPasswordField_newMdp;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField_Pseudo;
    // End of variables declaration//GEN-END:variables
    private FenPrincipale ancetre;
}
