/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FenPrincipale.java
 *
 * Created on 26 avr. 2012, 17:51:47
 */
package application.Vue;

import application.Modele.BaseLayer.Profil;
import framework.Client.Client;
import framework.Commun.IApplication;
import java.rmi.RemoteException;

/**
 *
 * @author Home
 */
public class FenPrincipale extends javax.swing.JFrame {

    /** Creates new form FenPrincipale */
    public FenPrincipale() {
        initComponents();
        this.setLocationRelativeTo(null);
        client = new Client("127.0.0.1:1099");
        ((FAQ)this.jPanelModule).setFen(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelLogin = new FenDecoMembre(this);
        jSeparator1 = new javax.swing.JSeparator();
        jPanelModule = new FAQ();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenufile = new javax.swing.JMenu();
        jMenuItemQuitter = new javax.swing.JMenuItem();
        jMenuProfil = new javax.swing.JMenu();
        jMenuItemModifier = new javax.swing.JMenuItem();
        jMenuForum = new javax.swing.JMenu();
        jMenuItemAccederForum = new javax.swing.JMenuItem();
        jMenuStockage = new javax.swing.JMenu();
        jMenuItemAccederStockage = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Application temoin");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanelLogin = new FenDecoMembre(this);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        getContentPane().add(jPanelLogin, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        getContentPane().add(jSeparator1, gridBagConstraints);

        javax.swing.GroupLayout jPanelModuleLayout = new javax.swing.GroupLayout(jPanelModule);
        jPanelModule.setLayout(jPanelModuleLayout);
        jPanelModuleLayout.setHorizontalGroup(
            jPanelModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanelModuleLayout.setVerticalGroup(
            jPanelModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );

        jPanelModule = new FAQ();

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(jPanelModule, gridBagConstraints);

        jMenufile.setText("File");

        jMenuItemQuitter.setText("Quitter");
        jMenuItemQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitterActionPerformed(evt);
            }
        });
        jMenufile.add(jMenuItemQuitter);

        jMenuBar1.add(jMenufile);

        jMenuProfil.setText("Profil");
        jMenuProfil.setEnabled(false);

        jMenuItemModifier.setText("Modifier");
        jMenuItemModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModifierActionPerformed(evt);
            }
        });
        jMenuProfil.add(jMenuItemModifier);

        jMenuBar1.add(jMenuProfil);

        jMenuForum.setText("Forum");
        jMenuForum.setEnabled(false);

        jMenuItemAccederForum.setText("Acceder");
        jMenuItemAccederForum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAccederForumActionPerformed(evt);
            }
        });
        jMenuForum.add(jMenuItemAccederForum);

        jMenuBar1.add(jMenuForum);

        jMenuStockage.setText("Stockage");
        jMenuStockage.setEnabled(false);

        jMenuItemAccederStockage.setText("Acceder");
        jMenuItemAccederStockage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAccederStockageActionPerformed(evt);
            }
        });
        jMenuStockage.add(jMenuItemAccederStockage);

        jMenuBar1.add(jMenuStockage);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenuItemAccederStockageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAccederStockageActionPerformed

    getContentPane().remove(jPanelModule);
    jPanelModule = new PanelStockage(this);
    java.awt.GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.weighty = 0.5;
    getContentPane().add(jPanelModule, gridBagConstraints);
    getContentPane().validate();
    this.pack();
}//GEN-LAST:event_jMenuItemAccederStockageActionPerformed

private void jMenuItemQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitterActionPerformed

    this.dispose();
}//GEN-LAST:event_jMenuItemQuitterActionPerformed

private void jMenuItemAccederForumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAccederForumActionPerformed

    getContentPane().remove(jPanelModule);
    jPanelModule = new PanelForum();
    java.awt.GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.weighty = 0.5;
    getContentPane().add(jPanelModule, gridBagConstraints);
    getContentPane().validate();
    this.pack();
    ((PanelForum) jPanelModule).setFenetrePrincipal(this);
}//GEN-LAST:event_jMenuItemAccederForumActionPerformed

    private void jMenuItemModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModifierActionPerformed
        
    getContentPane().remove(jPanelModule);
    jPanelModule = new FenProfil(this);
    java.awt.GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.weighty = 0.5;
    getContentPane().add(jPanelModule, gridBagConstraints);
    getContentPane().validate();
    this.pack();
        
    }//GEN-LAST:event_jMenuItemModifierActionPerformed

public void switchPanelLogin(Profil pr){
    profilClient = pr;
    java.awt.GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.5;
    if (jPanelLogin instanceof FenDecoMembre){
        getContentPane().remove(jPanelLogin);
        jPanelLogin = new FenCoMembre(this);
        getContentPane().add(jPanelLogin, gridBagConstraints);
        jMenuForum.setEnabled(true);
        jMenuStockage.setEnabled(true);
        jMenuProfil.setEnabled(true);
        jMenuItemAccederForum.doClick();
    }else{
        getContentPane().remove(jPanelLogin);
        jPanelLogin = new FenDecoMembre(this);
        getContentPane().add(jPanelLogin, gridBagConstraints);
        jMenuForum.setEnabled(false);
        jMenuStockage.setEnabled(false);
        jMenuProfil.setEnabled(false);
        getContentPane().remove(jPanelModule);
        jPanelModule = new FAQ();
        ((FAQ)this.jPanelModule).setFen(this);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(jPanelModule, gridBagConstraints);
    }
    getContentPane().validate();
    this.pack();
}

public void returnForum(){
    
    getContentPane().remove(jPanelModule);
    jPanelModule = new PanelForum();
    java.awt.GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.weighty = 0.5;
    getContentPane().add(jPanelModule, gridBagConstraints);
    getContentPane().validate();
    this.pack();
    
}

public void afficherAdmin(){
    
    getContentPane().remove(jPanelModule);
    jPanelModule = new Admin(this);
    java.awt.GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.weighty = 0.5;
    getContentPane().add(jPanelModule, gridBagConstraints);
    getContentPane().validate();
    this.pack();
    
}

public IApplication application(){
    return client.application();
}

public Profil profil(){
    return profilClient;
}

public void updateProfil() throws RemoteException{
    profilClient = application().getGestionProfil().getProfilByPseudo(profilClient.getPseudo());
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FenPrincipale().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuForum;
    private javax.swing.JMenuItem jMenuItemAccederForum;
    private javax.swing.JMenuItem jMenuItemAccederStockage;
    private javax.swing.JMenuItem jMenuItemModifier;
    private javax.swing.JMenuItem jMenuItemQuitter;
    private javax.swing.JMenu jMenuProfil;
    private javax.swing.JMenu jMenuStockage;
    private javax.swing.JMenu jMenufile;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelModule;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
    private Client client;
    private Profil profilClient=null;
}
