/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Inscription.java
 *
 * Created on 26 avr. 2012, 22:59:17
 */
package application.Vue;

import application.Modele.BaseLayer.Profil;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author NNJeremy
 */
public class Inscription extends javax.swing.JFrame {

    /** Creates new form Inscription */
    public Inscription(FenPrincipale anc) {
        initComponents();
        this.setLocationRelativeTo(getParent());
        ancetre = anc;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel_InsciptionTitre = new javax.swing.JLabel();
        jTextField_Pseudo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_Pseudo = new javax.swing.JLabel();
        jLabel_Mdp1 = new javax.swing.JLabel();
        jLabel_Mdp2 = new javax.swing.JLabel();
        jPasswordField_Mdp2 = new javax.swing.JPasswordField();
        jPasswordField_Mdp1 = new javax.swing.JPasswordField();
        jButton_Enrg = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nouveau Compte");

        jLabel_InsciptionTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_InsciptionTitre.setText("Inscription");

        jLabel_Pseudo.setText("Pseudo : ");

        jLabel_Mdp1.setText("Mot de passe : ");

        jLabel_Mdp2.setText("Vérification du mdp : ");

        jButton_Enrg.setText("Enregistrez-vous");
        jButton_Enrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EnrgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_InsciptionTitre, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Pseudo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_Mdp2)
                                    .addComponent(jLabel_Mdp1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField_Mdp1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(jTextField_Pseudo, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(jPasswordField_Mdp2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                    .addComponent(jButton_Enrg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_InsciptionTitre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Pseudo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_Mdp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Mdp1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_Mdp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Mdp2))
                .addGap(18, 18, 18)
                .addComponent(jButton_Enrg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_EnrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EnrgActionPerformed
        // TODO add your handling code here:
        if(!new String(this.jPasswordField_Mdp1.getPassword()).equalsIgnoreCase(new String(this.jPasswordField_Mdp2.getPassword())))
            JOptionPane.showMessageDialog(this, "Veuillez saisir des mots de passe identiques");
        else{
            try {
                if(ancetre.application().getGestionProfil().ajouterProfil(new Profil(this.jTextField_Pseudo.getText(), new String(this.jPasswordField_Mdp1.getPassword()))))
                    this.dispose();
                else
                    JOptionPane.showMessageDialog(this, "Erreur lors de la creation", "Creation impossible", JOptionPane.ERROR_MESSAGE);
            } catch (RemoteException ex) {
                ex.printStackTrace();
            }
        }
            
    }//GEN-LAST:event_jButton_EnrgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Inscription(new FenPrincipale()).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Enrg;
    private javax.swing.JLabel jLabel_InsciptionTitre;
    private javax.swing.JLabel jLabel_Mdp1;
    private javax.swing.JLabel jLabel_Mdp2;
    private javax.swing.JLabel jLabel_Pseudo;
    private javax.swing.JPasswordField jPasswordField_Mdp1;
    private javax.swing.JPasswordField jPasswordField_Mdp2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField_Pseudo;
    // End of variables declaration//GEN-END:variables
    private FenPrincipale ancetre;
}
